<a href="https://colab.research.google.com/github/19pa1a0431/ai/blob/master/numpy_programmes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
a=67
b=45
if(a>b):
  print(a)
else:
  print(b)  

67


In [6]:
import numpy as np
x=np.array([2,3,4,5])
print(x)


[2 3 4 5]


In [7]:
x=np.array([2,3,'n',5])
print(x)

['2' '3' 'n' '5']


In [9]:
b=np.linspace(start=1, stop=5 )
print(b)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [14]:
import numpy as np
d=np.arange(start=1,stop=10,step=2)
print(d)

[1 3 5 7 9]


In [15]:
import numpy as np
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
import numpy as np
np.random.rand(5) 

array([0.30183251, 0.7706032 , 0.66910323, 0.15187017, 0.12095633])

In [18]:
import numpy as np
np.random.rand(1,2)

array([[0.85593653, 0.48119377]])